from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]


CONTROL_RUNS = {
    "inverted": "semantic_constrained_transfer_router_inverted_age_only_1000",
    "all_slice": "semantic_constrained_transfer_router_all_target_slices_1000",
    "no_slice": "semantic_constrained_transfer_router_no_target_slices_1000",
}


def _load_run(run: str, value_name: str) -> pd.DataFrame:
    path = ROOT / "runs" / run / "semantic_constrained_transfer_router.csv"
    df = pd.read_csv(path)
    return df[["target", "repeat", "delta_vs_source"]].rename(columns={"delta_vs_source": value_name})


def _fmt_pct(value: float) -> str:
    return f"{100.0 * value:.2f}"


def _markdown(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(str(row[col]) for col in cols) + " |")
    return "\n".join(lines)


def _latex(df: pd.DataFrame, spec: str) -> str:
    def esc(value: object) -> str:
        text = str(value)
        return text.replace("%", r"\%").replace("<", r"$<$").replace(">", r"$>$")

    cols = list(df.columns)
    lines = [f"\\begin{{tabular}}{{{spec}}}", "\\toprule"]
    lines.append(" & ".join(esc(col) for col in cols) + r" \\")
    lines.append("\\midrule")
    for _, row in df.iterrows():
        lines.append(" & ".join(esc(row[col]) for col in cols) + r" \\")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--semantic-run", default="semantic_constrained_transfer_router_threshold1_1000")
    parser.add_argument("--bootstrap", type=int, default=20000)
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--out", type=Path, default=ROOT / "runs/semantic_router_control_bootstrap")
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)
    semantic = _load_run(args.semantic_run, "semantic_delta")
    rows = []
    paired_rows = []
    for control_name, run_name in CONTROL_RUNS.items():
        control = _load_run(run_name, "control_delta")
        merged = semantic.merge(control, on=["target", "repeat"], how="inner", validate="one_to_one")
        merged["diff"] = merged["semantic_delta"] - merged["control_delta"]
        merged["control"] = control_name
        paired_rows.append(merged)
        for target, group in merged.groupby("target"):
            diffs = group["diff"].to_numpy(dtype=float)
            n = len(diffs)
            boot_means = np.empty(args.bootstrap, dtype=float)
            for i in range(args.bootstrap):
                boot_means[i] = float(np.mean(diffs[rng.integers(0, n, size=n)]))
            rows.append(
                {
                    "control": control_name,
                    "target": target,
                    "n": n,
                    "mean_diff": float(np.mean(diffs)),
                    "mean_diff_ci_low": float(np.quantile(boot_means, 0.025)),
                    "mean_diff_ci_high": float(np.quantile(boot_means, 0.975)),
                    "p_boot_mean_le_0": float(np.mean(boot_means <= 0.0)),
                    "paired_win_rate": float(np.mean(diffs > 0.0)),
                    "paired_tie_rate": float(np.mean(np.isclose(diffs, 0.0, atol=1e-12))),
                }
            )

    result = pd.DataFrame(rows)
    paired = pd.concat(paired_rows, ignore_index=True)
    args.out.mkdir(parents=True, exist_ok=True)
    result.to_csv(args.out / "semantic_router_control_bootstrap.csv", index=False)
    paired.to_csv(args.out / "semantic_router_control_paired_deltas.csv", index=False)

    paper = result.copy()
    paper["Mean diff"] = paper["mean_diff"].map(_fmt_pct)
    paper["95% CI"] = [
        f"[{_fmt_pct(lo)}, {_fmt_pct(hi)}]"
        for lo, hi in zip(paper["mean_diff_ci_low"], paper["mean_diff_ci_high"])
    ]
    paper["P(mean<=0)"] = paper["p_boot_mean_le_0"].map(lambda x: f"{x:.4f}")
    paper["Win rate"] = paper["paired_win_rate"].map(lambda x: f"{x:.3f}")
    paper = paper[["control", "target", "n", "Mean diff", "95% CI", "P(mean<=0)", "Win rate"]]
    paper.to_csv(args.out / "semantic_router_control_bootstrap_paper.csv", index=False)

    lines = [
        "# Semantic Router Paired Bootstrap vs Controls",
        "",
        f"Semantic run: `{args.semantic_run}`",
        f"Bootstrap samples: `{args.bootstrap}`",
        "",
        _markdown(paper),
        "",
    ]
    (args.out / "SEMANTIC_ROUTER_CONTROL_BOOTSTRAP.md").write_text("\n".join(lines), encoding="utf-8")

    tex_lines = [
        "% Auto-generated by scripts/bootstrap_semantic_router_control_deltas.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\scriptsize",
        "\\caption{Paired bootstrap differences between the semantic router and negative-control routing rules. Mean differences are AUROC points over matched target resamples.}",
        "\\label{tab:semantic_router_paired_controls}",
        "\\resizebox{\\linewidth}{!}{%",
        _latex(paper, "llrcccc"),
        "}",
        "\\end{table}",
        "",
    ]
    (args.out / "semantic_router_control_bootstrap.tex").write_text("\n".join(tex_lines), encoding="utf-8")
    print(args.out / "SEMANTIC_ROUTER_CONTROL_BOOTSTRAP.md")


if __name__ == "__main__":
    main()
