from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "runs"
OUT = RUNS / "semantic_router_guard_sensitivity"


RUNS_TO_SUMMARIZE = [
    ("no_inner_guard", "none", RUNS / "semantic_constrained_transfer_router_threshold1_1000"),
    ("inner_guard_0.000", "0.000", RUNS / "semantic_constrained_transfer_router_guard0_1000"),
    ("inner_guard_0.005", "0.005", RUNS / "semantic_constrained_transfer_router_guard0p005_1000"),
    ("inner_guard_0.010", "0.010", RUNS / "semantic_constrained_transfer_router_guard0p01_1000"),
]


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _fmt_pct(value: Any) -> str:
    try:
        return f"{100.0 * float(value):+.2f}"
    except (TypeError, ValueError):
        return "NA"


def _fmt_prob(value: Any) -> str:
    try:
        return f"{float(value):.3f}"
    except (TypeError, ValueError):
        return "NA"


def _read_margin(run_dir: Path, fallback: str) -> str:
    summary_json = run_dir / "semantic_constrained_transfer_router_summary.json"
    if not summary_json.is_file():
        return fallback
    payload = json.loads(summary_json.read_text(encoding="utf-8"))
    margin = payload.get("inner_guard_margin")
    if margin is None:
        return fallback
    return f"{float(margin):.3f}"


def _selection_share(selection_rows: list[dict[str, str]], target: str, strategy: str) -> str:
    total = 0
    selected = 0
    for row in selection_rows:
        if row.get("target") != target:
            continue
        count = int(row.get("count", "0") or 0)
        total += count
        if row.get("selected_strategy") == strategy:
            selected += count
    if total == 0:
        return "NA"
    return f"{selected / total:.3f}"


def _to_md_table(rows: list[dict[str, str]], cols: list[str]) -> str:
    lines = [
        "| " + " | ".join(cols) + " |",
        "| " + " | ".join(["---"] * len(cols)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row.get(col, "") for col in cols) + " |")
    return "\n".join(lines)


def _to_latex_table(rows: list[dict[str, str]]) -> str:
    lines = [
        "% Auto-generated by scripts/build_semantic_router_guard_sensitivity.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{Semantic-router sensitivity to an inner guard fallback. Deltas are AUROC percentage points versus source-only; $p_{<0}$ is the split-level failure rate.}",
        "\\label{tab:semantic_router_guard_sensitivity}",
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "Guard & Target & Mean & Median & $p_{<0}$ & Deployed share \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(
            f"{row['guard_margin']} & {row['target']} & {row['mean_delta_pt']} & "
            f"{row['median_delta_pt']} & {row['p_delta_lt_0']} & {row['primary_strategy_share']} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    rows: list[dict[str, str]] = []
    missing: list[str] = []
    for run_name, fallback_margin, run_dir in RUNS_TO_SUMMARIZE:
        summary_rows = _read_csv(run_dir / "semantic_constrained_transfer_router_summary.csv")
        selection_rows = _read_csv(run_dir / "semantic_constrained_transfer_router_selection_counts.csv")
        if not summary_rows:
            missing.append(str(run_dir))
            continue
        margin = _read_margin(run_dir, fallback_margin)
        for item in summary_rows:
            target = item["target"]
            primary = "slice_gate" if target == "COUGHVID" else "logistic_stacking"
            rows.append(
                {
                    "run": run_name,
                    "guard_margin": margin,
                    "target": target,
                    "mean_delta_pt": _fmt_pct(item.get("mean_delta_vs_source")),
                    "median_delta_pt": _fmt_pct(item.get("median_delta_vs_source")),
                    "split_q2p5_pt": _fmt_pct(item.get("ci95_low")),
                    "split_q97p5_pt": _fmt_pct(item.get("ci95_high")),
                    "p_delta_lt_0": _fmt_prob(item.get("p_delta_lt_0")),
                    "p_delta_lt_1pt": _fmt_prob(item.get("p_delta_lt_1pt")),
                    "primary_strategy": primary,
                    "primary_strategy_share": _selection_share(selection_rows, target, primary),
                }
            )

    OUT.mkdir(parents=True, exist_ok=True)
    csv_path = OUT / "semantic_router_guard_sensitivity.csv"
    cols = [
        "guard_margin",
        "target",
        "mean_delta_pt",
        "median_delta_pt",
        "split_q2p5_pt",
        "split_q97p5_pt",
        "p_delta_lt_0",
        "p_delta_lt_1pt",
        "primary_strategy",
        "primary_strategy_share",
    ]
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=cols)
        writer.writeheader()
        writer.writerows([{col: row[col] for col in cols} for row in rows])

    md_lines = [
        "# Semantic-router guard sensitivity",
        "",
        "This table summarizes existing 1000-repeat semantic-router runs without rerunning the audit.",
        "",
        "The inner guard fallback sends a split to source-only when the target-calibration estimate is not sufficiently positive. It reduces risky deployments but can reduce mean gain, especially on TosCOVID.",
        "",
        "## Summary",
        "",
        _to_md_table(rows, cols),
        "",
        "## Interpretation",
        "",
        "- The no-inner-guard run gives the largest mean gains: COUGHVID +3.75pt and TosCOVID +3.99pt.",
        "- Guarded variants remain positive on both targets, but TosCOVID drops to about +2.1 to +2.3pt as fallback use rises.",
        "- COUGHVID keeps a stronger mean gain under guarded variants, around +2.9 to +3.4pt.",
        "- This supports reporting the main result as the semantic rule, while treating inner guards as a conservative deployment option rather than the headline claim.",
        "",
    ]
    if missing:
        md_lines.extend(["## Missing Inputs", "", *[f"- `{item}`" for item in missing], ""])
    (OUT / "SEMANTIC_ROUTER_GUARD_SENSITIVITY.md").write_text("\n".join(md_lines), encoding="utf-8")
    (OUT / "semantic_router_guard_sensitivity.tex").write_text(_to_latex_table(rows), encoding="utf-8")
    print(json.dumps({"rows": len(rows), "missing": missing, "out": str(OUT)}, indent=2))


if __name__ == "__main__":
    main()
