from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "runs"
OUT = RUNS / "semantic_router_subject_grouped_tables"


RUNS_TO_SUMMARIZE = [
    ("Semantic", RUNS / "semantic_constrained_transfer_router_subject_grouped_1000", "subject-disjoint intended semantics"),
    ("Inverted", RUNS / "semantic_constrained_transfer_router_subject_grouped_inverted_1000", "both targets routed incorrectly"),
    ("All-slice", RUNS / "semantic_constrained_transfer_router_subject_grouped_all_slice_1000", "Tos age slice remains unsafe"),
    ("No-slice", RUNS / "semantic_constrained_transfer_router_subject_grouped_no_slice_1000", "COUGHVID symptom slice disabled"),
]


def _read_summary(path: Path) -> dict[str, dict[str, str]]:
    summary_path = path / "semantic_constrained_transfer_router_summary.csv"
    if not summary_path.is_file():
        return {}
    with summary_path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    return {row["target"]: row for row in rows}


def _read_group_split(path: Path) -> str:
    summary_json = path / "semantic_constrained_transfer_router_summary.json"
    if not summary_json.is_file():
        return ""
    payload = json.loads(summary_json.read_text(encoding="utf-8"))
    return str(payload.get("group_split_column", ""))


def _pt(row: dict[str, str], key: str) -> str:
    return f"{100.0 * float(row[key]):.2f}"


def _ci(row: dict[str, str]) -> str:
    return f"[{100.0 * float(row['ci95_low']):.2f}, {100.0 * float(row['ci95_high']):.2f}]"


def main() -> None:
    rows = []
    for rule, run_dir, readout in RUNS_TO_SUMMARIZE:
        by_target = _read_summary(run_dir)
        group_split = _read_group_split(run_dir)
        if "COUGHVID" not in by_target or "TosCOVID" not in by_target:
            continue
        cough = by_target["COUGHVID"]
        tos = by_target["TosCOVID"]
        rows.append(
            {
                "Rule": rule,
                "COUGHVID mean": _pt(cough, "mean_delta_vs_source"),
                "COUGHVID split q2.5": _pt(cough, "ci95_low"),
                "Tos mean": _pt(tos, "mean_delta_vs_source"),
                "Tos split q2.5": _pt(tos, "ci95_low"),
                "Tos p(delta<0)": f"{float(tos['p_delta_lt_0']):.3f}",
                "Group split": group_split or "none",
                "Readout": readout,
            }
        )

    OUT.mkdir(parents=True, exist_ok=True)
    with (OUT / "semantic_router_subject_grouped_tables.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    md_lines = [
        "# Semantic Router Subject-Grouped Tables",
        "",
        "These tables summarize 1000-repeat semantic-router runs with target calibration/evaluation split by `subject_id`.",
        "",
        "| " + " | ".join(rows[0].keys()) + " |",
        "| " + " | ".join(["---"] * len(rows[0])) + " |",
    ]
    for row in rows:
        md_lines.append("| " + " | ".join(row.values()) + " |")
    md_lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "Subject-grouped resampling preserves the intended semantic pattern. COUGHVID is unchanged because its manifest has one recording per subject. TosCOVID mean gain drops from the row-level +3.99pt to +2.94pt, with higher split-tail risk, but semantic routing remains well above inverted and all-slice controls.",
            "",
        ]
    )
    (OUT / "SEMANTIC_ROUTER_SUBJECT_GROUPED_TABLES.md").write_text("\n".join(md_lines), encoding="utf-8")

    tex_lines = [
        "% Auto-generated by scripts/build_semantic_router_subject_grouped_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{Subject-grouped semantic-router controls. Deltas are AUROC percentage points versus source-only; split q2.5 is the 2.5\\% quantile of per-split deltas.}",
        "\\label{tab:semantic_router_subject_grouped}",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "Rule & COUGHVID mean & COUGHVID q2.5 & Tos mean & Tos q2.5 & Tos $p_{<0}$ \\\\",
        "\\midrule",
    ]
    for row in rows:
        tex_lines.append(
            f"{row['Rule']} & {row['COUGHVID mean']} & {row['COUGHVID split q2.5']} & "
            f"{row['Tos mean']} & {row['Tos split q2.5']} & {row['Tos p(delta<0)']} \\\\"
        )
    tex_lines.extend(["\\bottomrule", "\\end{tabular}", "}", "\\end{table}", ""])
    (OUT / "semantic_router_subject_grouped_tables.tex").write_text("\n".join(tex_lines), encoding="utf-8")
    print(json.dumps({"rows": len(rows), "out": str(OUT)}, indent=2))


if __name__ == "__main__":
    main()
